export const NEW_DATA_REQUEST = "NEW_DATA_REQUEST"
export const NEW_DATA_SUCCESS = "NEW_DATA_SUCCESS"
export const NEW_DATA_RESET   = "NEW_DATA_RESET"; 
export const NEW_DATA_FAIL    = "NEW_DATA_FAIL"; 

export const GET_DATA_REQUEST = "GET_DATA_REQUEST"
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS"
export const GET_DATA_RESET   = "GET_DATA_RESET"; 
export const GET_DATA_FAIL    = "GET_DATA_FAIL"; 